theta:
  rpcEndpoint: "http://127.0.0.1:16901/rpc"
node:
  skipInitializeTestWallets: true
rpc:
  enabled: true
  httpAddress: "127.0.0.1"
  httpPort: 19988
  wsAddress: "127.0.0.1"
  wsPort: 19989
  timeoutSecs: 600 
  maxConnections: 2048
log:
  levels: "*:debug"
