# Theta Subchain configuration
genesis:
  hash: "<YOUR_GENESIS_HASH>"
p2p:
  port: 12100
rpc:
  enabled: true
log:
  levels: "*:info"
  #levels: "*:debug"
consensus:
  minBlockInterval: 1
subchain:
  mainchainEthRpcURL: "http://localhost:18888/rpc"
  subchainEthRpcURL: "http://localhost:19888/rpc"
  chainRegistrarOnMainchain: "0x01Cb3B1D61E8E833FbC520370d02477e0f07a405"
  mainchainTFuelTB: "0x9747904F58bb8a83B9060fDF90d2A4CEDd63F840"
  mainchainTNT20TB: "0x5DeEDCB2ba97d59b00240506151BbC9cc86f014c"
  mainchainTNT721TB: "0x2364DDB56E9A98E016B5D3d372f648fCEA30c06C"
  mainchainTNT1155TB: "0x6A75D986911ECdDb2BF1a866Cfc0A33c9Ece1B32"
  updateInterval: 3000
  # use the numerical EVM chainID for <YOUR_EVM_chainID> below, e.g. 360998877 
  chainID: <YOUR_EVM_chainID>

